tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install 
      sudo apt-get install python-tk python-dev -y
      
  - command: |
      source venv/bin/activate
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview


