tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install pyautogui
      
  - command: |
      source venv/bin/activate
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview


